version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30

    working_directory: ~/code

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2
  build:
    jobs:
      - build