version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.08
      - image: cimg/base:2024.01

    working_directory: ~/code

    steps:
      - checkout

      - run:
          name: Install Java
          command: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

      - restore_cache:
          key: jars-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Lint Test
          command: ./gradlew lint test

      - run:
          name: Build Gradle
          command: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Run Tests
          command: ./gradlew test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2
  build:
    jobs:
      - build